# File: .github/workflows/deploy.yml

name: Linux_Container_Node_Workflow

on:
    push:
      branches:
        - test

permissions:
    id-token: write
    contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run az commands'
      run: |
        az account show
        az group list
        pwd

    - name: Log into the registry
      run: az acr login --name CRspringpetclinicDOB

    - run: |
        docker build . -t crspringpetclinicdob.azurecr.io:${{ github.sha }}
        docker push crspringpetclinicdob.azurecr.io:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'AS-spring-petclinic-DOB'
        images: 'crspringpetclinicdob.azurecr.io:${{ github.sha }}'